language: node_js
node_js: lts/*

stages:
  - lint
  - release

jobs:
  include:
    - stage: lint
      script:
        - npx commitlint-travis

    - stage: release
      # Advanced: optionally overwrite your default `script` step to skip the tests
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
