changesetBaseRefs:
  - main
  - origin/main

compressionLevel: mixed

enableGlobalCache: false

npmPublishAccess: public
npmPublishRegistry: "https://registry.npmjs.org"
npmAuthToken: ${NODE_AUTH_TOKEN}

yarnPath: .yarn/releases/yarn-4.0.2.cjs
